#!/usr/bin/env node

import canvas from 'canvas'
import atkinson from './index.js'

function dither(img, algo) {
    let cnvas = canvas.createCanvas(img.width, img.height)
    let ctx = cnvas.getContext('2d')
    ctx.drawImage(img, 0, 0)
    let imagedata = ctx.getImageData(0, 0, img.width, img.height)
    ctx.putImageData(algo(imagedata), 0, 0)
    return cnvas.createPNGStream()
}

function print(stream) {
    return new Promise( (_, reject) => {
        process.stdout.on('error', e => {
            if (e.code !== 'EPIPE') reject(e)
        })
        stream.pipe(process.stdout)
    })
}

function err(...msg) { console.error(...msg); process.exit(1) }

let DEBUG = !!process.env.DEBUG
let url = process.argv[2]
if (!url) err('Usage: atkinson url')

canvas.loadImage(url).then( r => dither(r, atkinson)).then(print).catch(e => {
    err(DEBUG ? e : `Error: ${e.message}`)
})
